spring:
  profiles:
    active: toby
  #    active: "@profileActive@"
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
    drop-first: false
  datasource:
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 200
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      # wall用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #禁止那些ip
        #deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

aps:
  # 是否异步记录用户操作日志
  openAopLog: true
  # Swagger文档路径
  docsPath: /docs
  # Swagger相关配置
  swagger:
    title: APS Backend API
    description: APS Backend API Documentation. If interested or confused, you can find out more about us at [github](https://github.com/NJUSEWebPlusPracticeGroupD)
    version: 1.0.0
    author: njuse-group-D
    url: https://software.nju.edu.cn/

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
  show-actuator: true
  group-configs:
  - group: users
    packages-to-scan: com.webplusgd.aps

---
spring:
  profiles: prod
  devtools:
    add-properties: false
server:
  port: 4000
  http2:
    enabled: true

---
spring:
  profiles: dev
  devtools:
    add-properties: true
  datasource:
    username: root
server:
  port: 4001
  http2:
    enabled: true

---
spring:
  profiles: steve
  devtools:
    add-properties: true
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apsdb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 981209880522Ff
server:
  port: 5200
  http2:
    enabled: true

---
spring:
  profiles: toby
  devtools:
    add-properties: true
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apsdb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123456
server:
  port: 5200
  http2:
    enabled: true

logging:
  level:
    org:
      optaplanner: info
optaplanner:
  solver:
    termination:
      spent-limit: 5s
