
package com.webplusgd.aps.webServiceClient.Erp.Entity;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MachineDoesNotExistFault", targetNamespace = "http://www.oldCompany.com/fault")
public class MachineDoesNotExistFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MachineDoesNotExistFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MachineDoesNotExistFault(String message, MachineDoesNotExistFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MachineDoesNotExistFault(String message, MachineDoesNotExistFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: Erp.Entity.MachineDoesNotExistFaultType
     */
    public MachineDoesNotExistFaultType getFaultInfo() {
        return faultInfo;
    }

}
