
package com.webplusgd.aps.webServiceClient.Erp.Service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ErpService", targetNamespace = "http://www.oldSystem.com/wsdl", wsdlLocation = "file:/D:/oceania-iter2/webclientTest/xml/wsdl/ErpSystem.wsdl")
public class ErpService
    extends Service
{

    private final static URL ERPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERPSERVICE_EXCEPTION;
    private final static QName ERPSERVICE_QNAME = new QName("http://www.oldSystem.com/wsdl", "ErpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/oceania-iter2/webclientTest/xml/wsdl/ErpSystem.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPSERVICE_WSDL_LOCATION = url;
        ERPSERVICE_EXCEPTION = e;
    }

    public ErpService() {
        super(__getWsdlLocation(), ERPSERVICE_QNAME);
    }

    public ErpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPSERVICE_QNAME, features);
    }

    public ErpService(URL wsdlLocation) {
        super(wsdlLocation, ERPSERVICE_QNAME);
    }

    public ErpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPSERVICE_QNAME, features);
    }

    public ErpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ErpPort
     */
    @WebEndpoint(name = "ErpPort")
    public ErpPort getErpPort() {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "ErpPort"), ErpPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErpPort
     */
    @WebEndpoint(name = "ErpPort")
    public ErpPort getErpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "ErpPort"), ErpPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPSERVICE_EXCEPTION!= null) {
            throw ERPSERVICE_EXCEPTION;
        }
        return ERPSERVICE_WSDL_LOCATION;
    }

}
